OBSERVATIONAL_DATASET_PATH = "datasets/0_observational_dataset.csv"

OBSERVATIONAL_CLEANED_PREPROCESSED_DATASET_PATH = "datasets/1_observational_cleaned_preprocessed_dataset.csv"

SYNTHETIC_EXPANDED_DATASET_PATH = "datasets/2_synthetic_expanded_dataset.csv"
SYNTHETIC_DATASET_ONLY_PATH = "datasets/2_synthetic_records_only.csv"
SYNTHETIC_EXPANSION_VALIDATION_REPORT = "datasets/2_synthetic_expansion_validation_report.csv"

OBSERVATIONAL_FEATURE_ENGINEERING_DATASET_PATH = "datasets/3_observational_feature_engineering_dataset.csv"
SYNTETIC_FEATURE_ENGINEERING_DATASET_PATH = "datasets/3_synthetic_feature_engineering_dataset.csv"

OBSERVATIONAL_DISCRETIZATION_CATEGORICAL_DATASET_PATH = "datasets/4_observational_discretization_categorical_dataset.csv"
SYNTETIC_DISCRETIZATION_CATEGORICAL_DATASET_PATH = "datasets/4_synthetic_discretization_categorical_dataset.csv"

OBSERVATIONAL_TRANSACTIONAL_DATASET_PATH = "datasets/5_observational_transactional_dataset.csv"
SYNTETIC_TRANSACTIONAL_DATASET_PATH = "datasets/5_synthetic_transactional_dataset.csv"

APRIORI_OBSERVATIONAL_OUTPUT_PATH = "outputARM/apriori_observational_output.csv"
FP_GROWTH_OBSERVATIONAL_OUTPUT_PATH = "outputARM/fpgrowth_observational_output.csv"
ECLAT_OBSERVATIONAL_OUTPUT_PATH = "outputARM/eclat_observational_output.csv"

APRIORI_SYNTHETIC_OUTPUT_PATH = "outputARM/apriori_synthetic_output.csv"
FP_GROWTH_SYNTHETIC_OUTPUT_PATH = "outputARM/fpgrowth_synthetic_output.csv"
ECLAT_SYNTHETIC_OUTPUT_PATH = "outputARM/eclat_synthetic_output.csv"

ARM_EXPERIMENT_SUMMARY_OBSERVATIONAL_PATH = "outputARM/arm_experiment_summary_observational.csv"
ARM_EXPERIMENT_SUMMARY_SYNTHETIC_PATH = "outputARM/arm_experiment_summary_synthetic.csv"

RESULTS_ALGORITHM_COMPARISON_TABLE_PATH = "outputARM/results_algorithm_comparison_table.csv"

RESULTS_TOP10_RULES_OBSERVATIONAL_PATH = "outputARM/results_top10_rules_observational.csv"
RESULTS_TOP10_RULES_SYNTHETIC_PATH = "outputARM/results_top10_rules_synthetic.csv"

RULE_OVERLAP_SUMMARY_ALL_ALGORITHMS_PATH = "outputARM/rule_overlap_summary_all_algorithms.csv"

RULE_OVERLAP_SUMMARY_GENERIC_PATH = "outputARM/rule_overlap_summary_{}.csv"

COMMON_RULES_OUTPUT_PATH = "outputARM/common_rules_{}.csv"
